### ISSUE TITLE
Reviewing page: add column with "date of submission" so they can be ranked based on that.

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#105]
Do we store a date stamp?
Would be good to include in approved projects as well perhaps?

**Comment by sverhoeven** [comment]
The projects are stored as files. The files have a modify timestamp, which corresponds to the time the file was written. 

Currently we don't store or use the timestamp anywhere.
We could besides read the contents of the file also store/show the modify timestamp.
