### ISSUE TITLE
Section 6 - make it required to add a "scan number" to "spectrum in a particular file" - otherwise there is still no gene cluster - molecule link

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#106]
MSV000084771 contains MS2 links specified as "spectrum in a particular file", without specifying which spectrum. Should specifying which actual spectrum be mandatory?
--> when choosing the option spectrum in particular file, the scan number should be mandatory.

**Comment by sverhoeven** [comment]
Fix merged into master branch will roll-out to production on Friday.
