### ISSUE TITLE
Submitter email is used where PI email is expected

### ISSUE THREAD

**Issue by sverhoeven** [iomega/paired-data-form#118]
On http://pairedomicsdata.bioinformatics.nl/projects/07be0785-0a06-49cc-b7a7-0bd82d8af58d.1 I expected the mail icon behind the PI `Anna Edlund` to go to her email, but the email adress of the summiter `galeti@health.ucsd.edu` is used.

**Comment by mschorn0713** [comment]
Many of the submissions put the submitter email as the PI email as well. I
can begin to fix these with the emails I have gathered for those PIs.

**Comment by sverhoeven** [comment]
This is also a [render issue](https://github.com/iomega/paired-data-form/blob/master/app/src/SubmitterInformation.tsx#L16), not only data problem.

**Comment by sverhoeven** [comment]
Fixed in #121
