### ISSUE TITLE
Download button on pending page yields incorrectly formatted json files

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#120]
**Describe the bug**
Download button on pending page yields incorrectly formatted json files.

**To Reproduce**
1. http://pairedomicsdata.bioinformatics.nl/pending
2. Download a pending project using the download button in the table on the page
3. Upload the downloaded json file into the add page
4. The validation fails

**Expected behavior**
Upload in add page should fill out the project information.

**Comment by sverhoeven** [comment]
The file downloaded on the pending page has an extra wrapper around the project like

```json
{
  "_id": "xxx",
  "project": { ... }
}
```

It should return the value of `project` property not the wrapped object.
