### ISSUE TITLE
Projects can have a `MIBiG_number` and `similar_MIBiG_number` in the same entry

### ISSUE THREAD

**Issue by sverhoeven** [iomega/paired-data-form#128]
Some projects have a `MIBiG_number` and `similar_MIBiG_number` in the same entry. 
It should be one of them, not both.

Probably because form was filled first with MIBiG_number and later switched to similar_MIBiG_number or vica versa.
The MIBiG_number is not cleared when switching to similar.

**Comment by sverhoeven** [comment]
For now will perform a manual migration to get rid of extra field.

**Comment by sverhoeven** [comment]
Data migration has been performed. data/approved/0ff7a302-49af-4130-a440-59e284d4d365.3.json data/approved/1b0dccac-5212-4dfd-a9f2-6fa953ab16bd.2.json data/approved/a4837d37-1df1-4153-b365-c06841574235.3.json have been corrected.

**Comment by justinjjvanderhooft** [comment]
Good catch Stefan - hadn't noticed that before....thanks for fixing!
