### ISSUE TITLE
Smiles string adds unwanted scrollbar

### ISSUE THREAD

**Issue by sverhoeven** [iomega/paired-data-form#147]
Looking at https://pairedomicsdata.bioinformatics.nl/projects/1b0dccac-5212-4dfd-a9f2-6fa953ab16bd.3 page, most of the bottom section is taken up by smile strings. This make the name, BGC and MS/MS only visible after scrolling to the side.
Could the smiles string be made smaller or moved as last column so we can see the whole link without scrolling?

**Comment by sverhoeven** [comment]
Chembl uses a text input to prevent scrolling for smiles and inchis see for example https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL4068896/ . It also adds clipboard/download buttons which might also be useful in PoDP.

**Comment by justinjjvanderhooft** [comment]
The SMILES can't be shortened, but moving the SMILES column to the end
could solve the unwanted scrolling....

**Comment by justinjjvanderhooft** [comment]
A clipboard could be used as well indeed. MiBIG is also using that.
