### ISSUE TITLE
List Tab does not function properly

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#167]
After the last release, the list tab does not work properly, and most likely the elastic search, as it does not list any projects and returns Bad Request on any input. 
![screenshot_2021-01-21_at_20 00 49](https://user-images.githubusercontent.com/2318072/105407670-4d4bdb00-5c2e-11eb-80a8-8b590d44d228.png)

**Comment by sverhoeven** [comment]
Server is back up
