### ISSUE TITLE
include project pages (with the BioSchemas) in the sitemap.xml

### ISSUE THREAD

**Issue by egonw** [iomega/paired-data-form#172]
**Is your feature request related to a problem? Please describe.**
If you include project pages (which have the BioSchemas annotation for DataSet) in the root `sitemap.xml`, Google indexer will be more likely to find them.

**Describe the solution you'd like**
I can imagine am autogenerated `sitemap-datasets.xml` to be included in the main `sitemap.xml`.

**See also**

- https://github.com/BioSchemas/bioschemas.github.io/pull/368

**Comment by sverhoeven** [comment]
The https://pairedomicsdata.bioinformatics.nl/sitemap.xml includes a link to https://pairedomicsdata.bioinformatics.nl/api/sitemap which dynamically produces list of project pages. Each project page has a DataSet entry in the header which is generated with React, see https://github.com/iomega/paired-data-form/blob/87de9335de0a6ea89b120a89068f4ae2fac8c7ec/app/src/PairedDataProject.tsx#L38-L51

In Google Search Console, a crawl was able to detect the DataSets. 

Not sure what else to do.

**Comment by egonw** [comment]
No, that should do it, I think.
