### ISSUE TITLE
Titles too long

### ISSUE THREAD

**Issue by sverhoeven** [iomega/paired-data-form#18]
Some values for the `title` field are a bit long. They should be split into a `title` and `description` fields.
For example the `genome_type` property.

**Comment by mschorn0713** [comment]
I included this and some other improvements in my latest commit, but unfortunately my latest commit isn't rendering properly and I can't figure out why.

**Comment by sverhoeven** [comment]
The https://json-schema-validator.herokuapp.com/syntax.jsp gives an error at https://github.com/iomega/paired-data-form/blob/57ce477fba23ebd91e5ffde27061668527aa385d/public/schema.json#L686

After removing the line it renders on https://mozilla-services.github.io/react-jsonschema-form/ somewhat the `gene_cluster_ms2_spectra_links` section is kaput and the React app will have problems due to renaming.

**Comment by mschorn0713** [comment]
Excellent; that json schema validator is nice. I fixed the error and will revert the names back so React app will be happy. It renders the last section gene_cluster_ms2_spectra_links when I put it in the playground.

**Comment by sverhoeven** [comment]
No please keep using the improved names, I will fix the React app after you have made the changes to the schema so that it renders correctly on https://mozilla-services.github.io/react-jsonschema-form/

**Comment by sverhoeven** [comment]
Ahh,  if I move the `"type":"string" into Compound_SMILES object it renders OK.

**Comment by mschorn0713** [comment]
schema now renders correctly

**Comment by sverhoeven** [comment]
Tables look OK now.
