### ISSUE TITLE
Typo in record MSV000078839

### ISSUE THREAD

**Issue by louwenjjr** [iomega/paired-data-form#187]
There is a typo in the record for MSV000078839.

For strain Streptomyces sp. TAA486 the link is:
ftp://massive.ucsd.edu/MSV000078839/spectrum/R5/AA486_R5_M.mzXML

While it should be:
ftp://massive.ucsd.edu/MSV000078839/spectrum/R5/TAA486_R5_M.mzXML

Cheers,
Joris

**Comment by justinjjvanderhooft** [comment]
I did update that line, but that broke something....now the system seems partly down!

**Comment by justinjjvanderhooft** [comment]
Updated now!
