### ISSUE TITLE
Wrong genome identifier for strain CNQ149 in MSV000078839

### ISSUE THREAD

**Issue by louwenjjr** [iomega/paired-data-form#190]
For Streptomyces sp. CNQ149 in record MSV000078839 (https://pairedomicsdata.bioinformatics.nl/projects/0ff7a302-49af-4130-a440-59e284d4d365.4), the genome identifier is incorrect as the the only identifier given is "Biosample: 1649593", which redirects to a biosample for a project on human, see below.

![image](https://user-images.githubusercontent.com/62542407/144040594-ea796021-c5ec-47a8-9ab7-668bd19240ec.png)

**Comment by justinjjvanderhooft** [comment]
Do you know the correct identifier? If so, could you update it in the project and resubmit it?

**Comment by louwenjjr** [comment]
Let me try to find it :)

**Comment by louwenjjr** [comment]
I can't seem to find it.. Not in NCBI nor in JGI. In the crusemann paper it says "not published" at the place of this strains identifier.

**Comment by justinjjvanderhooft** [comment]
Hmm, okay, in that case let's keep it this way for now....
