### ISSUE TITLE
Elastic Search - possible vulnerability

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#191]
**Describe the bug**
Current version of elastic search seems to be unsafe.
See email of WUR sys admin for further details:

Onder oplossen verstaan we :
Uitzetten onveilige containers
Verwijderen onveilige images
Eventueel installeren en starten van veilige versie
 
De nieuwste versie van de officiele docker heeft het lek gedicht.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by justinjjvanderhooft** [comment]
This is related to the log4j vulnerability (used within elastic search).

**Comment by sverhoeven** [comment]
I upgraded to https://github.com/elastic/elasticsearch/releases/tag/v7.16.2 which solves the log4j vulnerability.
