### ISSUE TITLE
Available projects isn't loading data

### ISSUE THREAD

**Issue by chasemc** [iomega/paired-data-form#195]
**Describe the bug**
Can't browse datasets

url:
https://pairedomicsdata.bioinformatics.nl/projects

issue:
![image](https://user-images.githubusercontent.com/18691127/150540534-6f94e038-d721-48fe-a4bf-d487c4ac6ca3.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]   Ubuntu Ubuntu 20.04.3 LTS
 - Browser [e.g. chrome, safari] Firefox 96.0 (64-bit)

**Comment by sverhoeven** [comment]
Thanks for the notification. One of the services had died. It has been restarted and projects are being rendered again.
