### ISSUE TITLE
Zenodo contains empty records

### ISSUE THREAD

**Issue by chasemc** [iomega/paired-data-form#210]
Not sure if this is on your side or Zenodo's but the latest Zenodo release seems to be corrupted
https://zenodo.org/record/6024659

![image](https://user-images.githubusercontent.com/18691127/153865551-d085d8f5-9550-4744-ab77-4e8bec7b7199.png)

**Comment by sverhoeven** [comment]
Thanks for reporting. I updated the zip library and created a new Zenodo record https://zenodo.org/record/6024659 which looks problem free.

Can you test it?

**Comment by chasemc** [comment]
Looks good
