### ISSUE TITLE
Add label field for genomes

### ISSUE THREAD

**Issue by sverhoeven** [iomega/paired-data-form#31]

**Comment by mschorn0713** [comment]
- add genome label with description to schema

**Comment by sverhoeven** [comment]
I started implementing it on the genome-label branch.

@mschorn0713 can you add a proper title/description to https://github.com/iomega/paired-data-form/blob/genome-label/public/schema.json#L160-L163 ?

**Comment by sverhoeven** [comment]
Thanks @mschorn0713

Genome label has been merged into master branch.
