### ISSUE TITLE
Example BGC-MS2 links

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#33]
Fill in example BCG-MS2 links for sample data from Cruseman dataset; will be used in "load example data" feature

**Comment by justinjjvanderhooft** [comment]
I have updated the example json file with BGC-MF and a BGC-molecule link. 
I sent you the json through Slack and you can also find it on the drive in PairedDataPlatform/JSONscheme_webform - it is called paired_datarecord_MSV000078839_example.json

**Comment by justinjjvanderhooft** [comment]
Stefan, could you try implement the "load example" button?

**Comment by sverhoeven** [comment]
Duplicated of #30

**Comment by sverhoeven** [comment]
Button was added next to other buttons to load the example json file.
