### ISSUE TITLE
Table download fixes

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#37]
Extraction solvent and other individual instrumentation methods display in the table downloaded. We should only have the labels in the table.

**Comment by mschorn0713** [comment]
Also it appears that sample growth time is in the downloaded table.

**Comment by sverhoeven** [comment]
When uploading a file with the `upload links` button in the `Links between genomes and metabolomics data` then the app can construct the links and their foreign tables aka genome, sample, extraction and instrument.

A download file with just the ms filename and the labels can not be imported without having all the labels resolving to a foreign table.

**Comment by sverhoeven** [comment]
Decided to have only `Genome/Metagenome	Location of metabolomics data file	Sample Growth Conditions	Extraction Method	Instrumentation Method` columns in the links between genomes and metabolomics download file. 

As it makes code much simpler and wysiwig.

When uploading the file in the form a warning will be displayed if a label used in the file does not exist in the form.
