### ISSUE TITLE
Lars' suggestions on improving the form

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#39]
- For collision I guess we expect an integer number, eV being the unit: would be good to specify, to avoid ending up with strings ("30 eV") that are much harder to work with.
- Similar for Mass range: lets give an example (something like "e.g. 100-800 for a range from 100 Da to 800 Da")
Under Links between genomes and metabolomics data:
-  Where can I find the "Location of metabolomics data file" for a given massive ID? For example I went here, but didn't see the link to an mzXML:
https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=b235c4c537a64fbeb96243d01418d1cc&view=advanced_view 
Ah, I guess have to go to click on ftp://massive.ucsd.edu/MSV000083540. Maybe it is useful to add this info in the text ("E.g. In a Massive Dataset Information panel, click on the FTP download link and subsequently on "raw" to get to the URL for the  mzXML file)

**Comment by sverhoeven** [comment]
* 45e93b11117dc9c04d327a1e74da5561b1f7960e improved data file description
* 86af60f9cde194005d86b3558dcfd873b0e893b5 added mass range example in it's description
