### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#4]
Pre-populate or create drop down lists of previously entered information in Genome, Sample Prep, Extraction Method, and Instrumentation Method

**Comment by sverhoeven** [comment]
When you add a link between genomes and metabolomics data the drop down lists are populated.

Still to do:
* [x] validate links
* [ ] update drop down list when Genome, Sample Prep, Extraction Method, and Instrumentation Method change

**Comment by sverhoeven** [comment]
Validate on submit added in 236456225e0340970e73b90e58bbed6476da2980

**Comment by sverhoeven** [comment]
Not going to update drop down when label changes. 
During form validation a drop downs with show error that the label is invalid and a new selection must be made.
