### ISSUE TITLE
Unclear which fields are mandatory

### ISSUE THREAD

**Issue by sverhoeven** [iomega/paired-data-form#42]
It is currently not clear enough which fields are mandatory or optional.

A solution could be to use different colors, but this might be to busy.

**Comment by justinjjvanderhooft** [comment]
This is important as some people still feel "overwhelmed" by the options....

 - [ ] make publication URL optional but indicate that it is a nice option to promote your study/work

**Comment by sverhoeven** [comment]
Replace `*` with `(required)`
