### ISSUE TITLE
General Schema improvements

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#47]
- [x] Add Project ID field to schema (not visible on add form)
- [x] Copy buttons in Project Page to top of page
- [x] Change Project ID size in Project Page
- [x] Add numbers to Section titles
~~- [ ] Decide if we want to move the create a label field up to the top of each section~~

**Comment by sverhoeven** [comment]
Adding id to schema is more disruptive as it needs backend api changes as well, will fix in https://github.com/iomega/paired-data-form/tree/project-id2schema branch.

**Comment by sverhoeven** [comment]
Moved project id to own issue #70
