### ISSUE TITLE
Genome section improvements

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#48]
- [x] Add possibility to add JGI ID for genome and metagenome
~~- [ ] Add more metagenome sample fields: sample handling, cell enrichment, etc~~
- [x] Change Genome/Metagenome description pop up and change placeholder text
- [x] Replace field Academic institution with OrchID for researcher submitting

**Comment by sverhoeven** [comment]
Orcid should be part of schema

**Comment by sverhoeven** [comment]
Use `at least one accession/id should be entered` as placeholder in uischema

**Comment by mschorn0713** [comment]
- [ ] get proper JGI terminology/examples when JGI server is up

**Comment by sverhoeven** [comment]
JGI server is back up. I added genome [641228474](https://img.jgi.doe.gov/cgi-bin/m/main.cgi?section=TaxonDetail&taxon_oid=641228474) and for metagenome [3300005805](https://img.jgi.doe.gov/cgi-bin/m/main.cgi?section=TaxonDetail&page=taxonDetail&taxon_oid=3300005805) as examples to the schema.
