### ISSUE TITLE
Sample Preparation schema improvements

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#49]
- [x] Add fungal media and other media specified by early user feedback
- [x] Links to Wikipedia/other ontology 
- [x] Add to "Other" description: can specify media components, check for purity
- [x] Add box for link/reference to "other" media when "other" is selected
- [x] Add shaking RPMs (optional)
- [x] Add other kinds of flasks to aeration section: conical tubes, deep-well plates, and other
- [x] Add units for temperature and growth time in headers
- [x] Other parameters requested by early users: volume of culture--add to Medium details section if liquid is selected ~~check for purity~~
- [x] move metagenome sections to "Medium details" with extra radio button

**Comment by sverhoeven** [comment]
@justinjjvanderhooft on ontology
@mschorn0713 add mediums, other descrip, shaking, descriptions
@sverhoeven move metagenome to medium details column + volume

**Comment by sverhoeven** [comment]
Also grouped growth temp, duration and phase into single column/object

**Comment by sverhoeven** [comment]
Found [MicrO: an ontology of phenotypic and metabolic characters, assays, and culture media found in prokaryotic taxonomic descriptions](http://obofoundry.org/ontology/micro).

The downloaded MicrO.owl contains a `microbiological culture medium` branch with medium definitions including ingredients, sadly it's IRI give not found errors. So the ontology can not be used in our web application.

**Comment by sverhoeven** [comment]
Keep using existing urls, as we could not find a single ontology for each field. See #63
