### ISSUE TITLE
MS2-BGC linking section schema improvements

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#52]
~~- [ ] For MS2, provide the URL for the mass spectrum with the molecule to link: if you can give an example to users of a GNPS link to molecular network (molecular family), or for GNPS link to cluster spectra of a single molecule, it will be more clear to users, what they should be providing. Like what is done for massive dataset~~
~~- [ ] Task ID and Cluster index as option to make the URL, instead of MS2 scan number~~

**Comment by justinjjvanderhooft** [comment]
- [ ] add info text on purpose of this section: to link gene clusters to mass spectra representing molecules - and that this list does not need to be exhaustive. Also stress that this is to link MIBIG or MIBIG matched gene clusters [this needs to be explained as well, i.e., gene cluster with high similarity to one in MIBIG but from a different origin (species)] to spectra. A new validated gene cluster should be submitted to MIBIG. This is to avoid confusion.

**Comment by justinjjvanderhooft** [comment]
- [x] change "MS2 URL file" title to "Mass spectrometry fragmentation file (mzML/mzXML/MGF/MSP)"
