### ISSUE TITLE
Introduction text - things to make clearer

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#55]
- [ ] make purpose(s) clearer: i.e., record available paired data sets with minimal required data to: i) allow to find links between spectral features / molecules and species, and ii) allow to find increased links between genome and metabolome through computational approaches

- [ ] make clearer why we need the minimal metadata we collect: to make comparison (ontologies!) and reuse by others possible

- [ ] make clearer we do not store data but link out to publicly available data

**Comment by sverhoeven** [comment]
[ ] Link section of image should be simpler.

Maybe also link image to add page.
