### ISSUE TITLE
Create statistics page

### ISSUE THREAD

**Issue by sverhoeven** [iomega/paired-data-form#65]

**Comment by sverhoeven** [comment]
Current stats:

* Overall
  * Number of projects
  * Number of unique principal investigators
  * Number of unique metabolome samples (spectra urls)
* Top principal investigators
* Instrument types
* Growth mediums
* Top solvents
* Genome types
* Top species

**Comment by sverhoeven** [comment]
Still needs 
* [ ] to be deployed to production 
* [ ] enrichments fetched for all entries in production

**Comment by sverhoeven** [comment]
All projects in production where tested succefully on a local copy. They all can be enriched and the stats page.

Page looks like :

![image](https://user-images.githubusercontent.com/1713488/75352716-7f33b080-58aa-11ea-9f42-8591cad3cd06.png)

**Comment by justinjjvanderhooft** [comment]
Looking nice Stefan! Shall we add top submitters as well? :-)

**Comment by mschorn0713** [comment]
It does look great! Another suggestion: instead of Growth Mediums, it
should be Growth Media.

Thanks!
Michelle

**Comment by sverhoeven** [comment]
Feedback incorporated:
![image](https://user-images.githubusercontent.com/1713488/75358767-b8245300-58b3-11ea-824b-13d2b56dfb8e.png)

**Comment by sverhoeven** [comment]
Stats page is online
