### ISSUE TITLE
Checklist before adding a project

### ISSUE THREAD

**Issue by sverhoeven** [iomega/paired-data-form#66]
Prepare user for which date must be prepared before creating a project.

Checklist should be part of add page

**Comment by mschorn0713** [comment]
Checklist before starting your submission:
-	Deposit metabolomics data in MASSive or MetaboLights and make the data publically available
-	Deposit assembled genomes/metagenomes to a public database (NCBI, JGI, MGnify) and make them publically available
-	Have the basic methods used available for reference

Only if connecting a BGC to molecule/molecular family:
-	Deposit the cluster in MIBiG and have the BGC ID number available
-	Have the SMILES (textual representation of the structure) available
-	Locate the MS2 scan or molecular family ID

Pro Tips:
-	Load the sample data to get an idea of how to fill out the form.
-	To save your work, complete section 2 for at least one sample and make one link, then press the Preview button, scroll down to the table created and press the Download button. You can later Upload this file to continue working. All validation errors must be resolved before you can download the file.

**Comment by mschorn0713** [comment]
Please add to the first section:
-	Locate the URLs for each metabolomics sample in the repository
