### ISSUE TITLE
Detect spaces in ftp massive URIs and replace by %20

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#75]
Or warn users they cannot enter spaces in the URI

**Comment by mschorn0713** [comment]
Put warning in descriptions for any field requiring URI (most important is the massive one)

**Comment by sverhoeven** [comment]
Reopened because https://github.com/iomega/paired-data-form/tree/MichelleSchemaChanges branch has not been merged in master branch yet.

**Comment by justinjjvanderhooft** [comment]
I don't see the warnings appearing in the form yet....

**Comment by mschorn0713** [comment]
We implemented this as a warning in the description--so in the sections which require a URI, the description contains: "Warning, there cannot be spaces in the URI."

**Comment by justinjjvanderhooft** [comment]
Ok - all good now! I can see the warning. We could add solutions later (i.e., replace spaces by "+")
