### ISSUE TITLE
final schema improvements

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#76]
- [x] Add erlenmeyer flask to aeration section
- [x] Add XAD resins and/or Other option to extraction section
- [x] Add links to relevant websites (MIBiG, GNPS, MaSSIVE)

**Comment by mschorn0713** [comment]
Michelle will do the first two tasks, Stefan the last task (links to websites)

**Comment by sverhoeven** [comment]
Created pull request #79 which has adds support for html in the descriptions. Also has some examples of links in the json schema.

**Comment by sverhoeven** [comment]
Reopened because https://github.com/iomega/paired-data-form/tree/MichelleSchemaChanges branch has not been merged in master branch yet.
