### ISSUE TITLE
Duplicate/copy button

### ISSUE THREAD

**Issue by mschorn0713** [iomega/paired-data-form#77]
Add option to duplicate Sample prep/extraction/instrumentation methods for quick duplication/modification of methods.

**Comment by sverhoeven** [comment]
The form library already has similar issue https://github.com/rjsf-team/react-jsonschema-form/issues/1261

The ArrayFieldTemplate can be customized to add buttons, but implementing the copy action requires changes to rjsf which have not been implemented.
