### ISSUE TITLE
Add information on who made (and runs) the platform.

### ISSUE THREAD

**Issue by florian-huber** [iomega/paired-data-form#86]
Some people I know got aware of the platform based on twitter activity, and asked me who was involved in that project.
I think it would be nice to add some information on the people that were involved in making it (mostly Stefan, Justin, Michelle, Marnix I guess). One could also include Wageningen University and the eScience center?
All of this could be added to bottom of the start page.

**Comment by sverhoeven** [comment]
Does the http://pairedomicsdata.bioinformatics.nl/about page have enough information?
