### ISSUE TITLE
Validation gene cluster - molecule link entry information on add page (required fields)

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#94]
When insufficient details on a gene cluster - molecule link are provided, and a user submits the information for review, the add page blanks and freezes and the information gets lost. The required fields should be validated instead....

**Comment by mschorn0713** [comment]
In my experience, the blank page/freeze happens when trying to Preview--I haven't tried to submit for review yet to replicate this error.

**Comment by justinjjvanderhooft** [comment]
Looks like we can improve the information as well:

I think I finally (!) figured out what was tripping me up.

For the MiBIG number, I was inserting "BGC0000259" but it actually needs just an integer 259. If you put a non-integer in there it gives the blank page and loses everything. Seems like an easy mistake to make (i have been making it for the last couple of days!)

**Comment by sverhoeven** [comment]
Schema changed rolled back, as current projects become invalid.

**Comment by sverhoeven** [comment]
Let's make strain", "coordinates fields recommended, but not required.

Check all projects in production against new schema, any invalid entries will fix ourselves or ask the submitter.

**Comment by sverhoeven** [comment]
Lets change the `MIBiG_number` and `similar_MIBiG_number` fields to string type with BGCxxxxx regexp.

**Comment by sverhoeven** [comment]
Fix merged into master branch will roll-out to production on Friday.
