### ISSUE TITLE
Enable multiple authors for submission

### ISSUE THREAD

**Issue by chanana** [iomega/paired-data-form#97]
Please make an option to add additional persons involved in the generation of the data. In my case, the genome assembly and mass spectrometry were carried out by different people but only one of us is getting the credit.

**Comment by justinjjvanderhooft** [comment]
Thanks for your feedback - in the form it is possible to add several names in the field, but we will discuss whether to formalise this more.

**Comment by sverhoeven** [comment]
We can add a secondary submitter with name and email field.

**Comment by sverhoeven** [comment]
Fix merged into master branch will roll-out to production on Friday.
